version: "3"

services:
  worker_vad:
    build: .
    environment:
      QUEUE_SERVER: "localhost:5672"
      FILES_SERVER: "localhost:3001"
      INPUT_QUEUE_NAME: "vad_in"
      OUTPUT_QUEUE_NAME: "vad_out"